### ISSUE TITLE
V0.33 not working

### ISSUE THREAD

**Issue by weaselclown** [RAYTRAC3R/RAYTRAC3R-s-Cosmetics#1]
Doesn't do anything when installing or updating on HLS.
When trying to import via ZIP, it says "Failed to import mod: Expecting ',' delimiter: line 5 column 5 (char 117).

I tried again and now it works, just wasn't working earlier, thank you!

**Comment by RAYTRAC3R** [comment]
Yeah, I messed up one of the JSONs but quickly fixed it. Thank you for trying to let me know though!
